# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookstore_development
  username: bookstore
  password: books123
  host: localhost
  port: 5432

test:
  <<: *default
  database: bookstore_test
  host: localhost
  port: 5432
  username: bookstore
  password: books123

production:
  <<: *default
  database: bookstore_production
  username: bookstore
  password: books123